import type { Industry, StartupStage } from '@/types';

export const INDUSTRIES: Industry[] = [
  'AI/ML', 'SaaS', 'FinTech', 'HealthTech', 'EdTech',
  'CleanTech', 'E-Commerce', 'DeepTech', 'Gaming', 'Web3',
  'Marketplace', 'Consumer', 'BioTech', 'SpaceTech', 'PropTech',
];

export const STARTUP_STAGES: StartupStage[] = [
  'Idea', 'MVP', 'Early Revenue', 'Scaling',
];

export const STAGE_COLORS: Record<StartupStage, string> = {
  'Idea': 'bg-slate-500/20 text-slate-300 border-slate-500/30',
  'MVP': 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  'Early Revenue': 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
  'Scaling': 'bg-purple-500/20 text-purple-300 border-purple-500/30',
};

export const INDUSTRY_ICONS: Record<Industry, string> = {
  'AI/ML': '🤖',
  'SaaS': '☁️',
  'FinTech': '💳',
  'HealthTech': '🏥',
  'EdTech': '📚',
  'CleanTech': '🌱',
  'E-Commerce': '🛒',
  'DeepTech': '🔬',
  'Gaming': '🎮',
  'Web3': '⛓️',
  'Marketplace': '🏪',
  'Consumer': '👥',
  'BioTech': '🧬',
  'SpaceTech': '🚀',
  'PropTech': '🏠',
};

export const AI_INTERVIEW_QUESTIONS = [
  'What industries or sectors do you primarily invest in, and why?',
  'What level of traction do you typically expect before investing?',
  'What makes a founder exceptionally attractive to you as an investor?',
  'How quickly can you make an investment decision after first meeting?',
  'Describe your typical involvement post-investment with portfolio companies.',
];

export const MOCK_STARTUP_PROFILES = [
  {
    id: 'startup-1',
    userId: 'user-s1',
    startupName: 'NeuralPay',
    industry: 'FinTech' as Industry,
    problemStatement: 'Cross-border payments are slow, expensive, and opaque for SMBs.',
    solution: 'AI-powered payment routing that reduces costs by 70% and settles in seconds.',
    stage: 'Early Revenue' as StartupStage,
    fundingRequired: 2000000,
    teamSize: 8,
    location: 'San Francisco, CA',
    traction: '$120K MRR, 340 enterprise clients',
    aiScores: {
      marketPotential: 92,
      teamStrength: 78,
      problemClarity: 88,
      overall: 86,
      feedback: 'Strong market opportunity with clear differentiation. Team execution capability needs more evidence.',
    },
    createdAt: '2025-01-15',
    founderName: 'Aisha Chen',
    founderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'startup-2',
    userId: 'user-s2',
    startupName: 'EduMorph',
    industry: 'EdTech' as Industry,
    problemStatement: 'Traditional education fails to adapt to individual learning speeds.',
    solution: 'Adaptive AI curriculum that personalizes content in real-time based on student performance.',
    stage: 'MVP' as StartupStage,
    fundingRequired: 750000,
    teamSize: 4,
    location: 'Austin, TX',
    traction: '2,400 beta users, 68% retention',
    aiScores: {
      marketPotential: 85,
      teamStrength: 72,
      problemClarity: 91,
      overall: 82,
      feedback: 'Excellent problem clarity and strong retention metrics for an MVP stage.',
    },
    createdAt: '2025-02-01',
    founderName: 'Marcus Williams',
    founderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'startup-3',
    userId: 'user-s3',
    startupName: 'GreenVault',
    industry: 'CleanTech' as Industry,
    problemStatement: 'Carbon credit markets are inaccessible to small businesses.',
    solution: 'Fractional carbon credit marketplace with real-time verification blockchain.',
    stage: 'Scaling' as StartupStage,
    fundingRequired: 8000000,
    teamSize: 22,
    location: 'New York, NY',
    traction: '$2.1M ARR, 12 enterprise partnerships',
    aiScores: {
      marketPotential: 95,
      teamStrength: 89,
      problemClarity: 87,
      overall: 90,
      feedback: 'Exceptional traction and team credentials. Market timing is perfect with ESG mandates.',
    },
    createdAt: '2024-11-20',
    founderName: 'Sofia Rodriguez',
    founderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'startup-4',
    userId: 'user-s4',
    startupName: 'MindBridge AI',
    industry: 'HealthTech' as Industry,
    problemStatement: 'Mental health support is unavailable to 80% of those who need it.',
    solution: 'AI therapist companion with crisis detection and seamless therapist handoff.',
    stage: 'Early Revenue' as StartupStage,
    fundingRequired: 3500000,
    teamSize: 11,
    location: 'Boston, MA',
    traction: '18K active users, $45K MRR',
    aiScores: {
      marketPotential: 94,
      teamStrength: 83,
      problemClarity: 96,
      overall: 91,
      feedback: 'Outstanding problem clarity and meaningful social impact. Strong unit economics.',
    },
    createdAt: '2025-01-08',
    founderName: 'Daniel Kim',
    founderAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
  },
];

export const MOCK_INVESTOR_PROFILES = [
  {
    id: 'investor-1',
    userId: 'user-i1',
    investorName: 'Victoria Hartwell',
    firmName: 'Apex Ventures',
    bio: 'Partner at Apex Ventures with 15+ years backing B2B SaaS and FinTech. Former founder (2 exits). Board member at 8 companies.',
    minInvestment: 500000,
    maxInvestment: 5000000,
    preferredIndustries: ['FinTech', 'SaaS', 'AI/ML'] as Industry[],
    preferredStages: ['MVP', 'Early Revenue'] as StartupStage[],
    portfolioCompanies: ['Stripe', 'Plaid', 'Brex', 'Mercury'],
    location: 'San Francisco, CA',
    interviewCompleted: true,
    qualityScore: {
      experience: 96,
      investmentClarity: 91,
      founderFriendliness: 88,
      decisionSpeed: 85,
      overall: 90,
      badge: 'Platinum' as const,
    },
    createdAt: '2024-10-01',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'investor-2',
    userId: 'user-i2',
    investorName: 'James Okafor',
    firmName: 'Deep Impact Capital',
    bio: 'Impact investor focused on CleanTech and HealthTech. Former McKinsey partner. ESG-first investment thesis.',
    minInvestment: 1000000,
    maxInvestment: 10000000,
    preferredIndustries: ['CleanTech', 'HealthTech', 'BioTech'] as Industry[],
    preferredStages: ['Early Revenue', 'Scaling'] as StartupStage[],
    portfolioCompanies: ['Oatly', 'Impossible Foods', 'Carbon Cure'],
    location: 'London, UK',
    interviewCompleted: true,
    qualityScore: {
      experience: 88,
      investmentClarity: 93,
      founderFriendliness: 82,
      decisionSpeed: 79,
      overall: 86,
      badge: 'Gold' as const,
    },
    createdAt: '2024-11-15',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
  },
  {
    id: 'investor-3',
    userId: 'user-i3',
    investorName: 'Priya Nakamura',
    firmName: 'Horizon Seed Fund',
    bio: 'Angel investor and GP at Horizon Seed. Technical background in ML. Passionate about EdTech and consumer AI.',
    minInvestment: 100000,
    maxInvestment: 500000,
    preferredIndustries: ['AI/ML', 'EdTech', 'Consumer'] as Industry[],
    preferredStages: ['Idea', 'MVP'] as StartupStage[],
    portfolioCompanies: ['Duolingo (early)', 'Notion', 'Perplexity'],
    location: 'Tokyo / Remote',
    interviewCompleted: false,
    createdAt: '2025-01-20',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face',
  },
];
